Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "loadbalancer"
  config.vm.network "private_network", ip: "192.168.33.254"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y unzip nginx
    wget -q https://releases.hashicorp.com/consul-template/0.19.5/consul-template_0.19.5_linux_amd64.zip
    unzip consul-template_0.19.5_linux_amd64.zip
    rm -f consul-template_0.19.5_linux_amd64.zip
    chmod +x consul-template
    mv consul-template /usr/local/bin/consul-template
    mkdir /etc/consul-template.d
    cp /vagrant/nginx-vhost.conf.ctmpl /etc/consul-template.d/nginx-vhost.conf.ctmpl
  SHELL
end
