Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "consul-server"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y unzip
    wget -q https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip
    unzip consul_1.3.0_linux_amd64.zip
    rm -f consul_1.3.0_linux_amd64.zip
    chmod +x consul
    mv consul /usr/local/bin/consul
    mkdir -p /var/lib/consul
    mkdir -p /usr/share/consul
    mkdir -p /etc/consul/conf.d
  SHELL
end
