nodes = [
  { :hostname => 'node-1',  :ip => '192.168.33.11' },
  { :hostname => 'node-2',  :ip => '192.168.33.12' },
  { :hostname => 'node-3',  :ip => '192.168.33.13' },
  { :hostname => 'node-4',  :ip => '192.168.33.14' },
  { :hostname => 'node-5',  :ip => '192.168.33.15' },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network :private_network, ip: node[:ip]
    end
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx unzip
    wget -q https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip
    unzip consul_1.3.0_linux_amd64.zip
    rm -f consul_1.3.0_linux_amd64.zip
    chmod +x consul
    mv consul /usr/local/bin/consul
    mkdir -p /var/lib/consul
    mkdir -p /usr/share/consul
    mkdir -p /etc/consul/conf.d
    ln -s /vagrant/webserver.json /etc/consul/conf.d/webserver.json
    echo $(hostname) > /var/www/html/index.html
  SHELL
end
